# Generated by Django 5.0 on 2024-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('extra_skills', models.CharField(choices=[('1', 'English'), ('2', 'Math'), ('3', 'Programming'), ('4', 'Communication'), ('5', 'Psychology'), ('6', 'Korean Language'), ('7', 'Chinese'), ('8', 'Kind')], default='8', max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('information', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
