# Generated by Django 5.0 on 2024-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('sinfi', models.CharField(max_length=50, null=True)),
                ('maktabi', models.CharField(max_length=50, null=True)),
                ('tel_raqam', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
