# Generated by Django 5.0 on 2024-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
