# Generated by Django 5.0 on 2024-11-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_subject_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
